apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cn-turkey-bb-demo'
spec:
  project: default
  source:
    repoURL: 'https://github.com/huseyinyener/argocd-go-k8s.git'
    path: ./k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
